trigger:
  branches:
    include:
      - main
  paths:
    include:
      - app/*
      - k8s/*
      - azure-pipelines.yml

variables:
  acrName: devopsecomacr1234.azurecr.io
  services: frontend users products cart

stages:
- stage: Build
  displayName: 'Build and Push Docker Images'
  jobs:
  - ${{ each service in variables.services }}:
    - job: Build_${{ service }}
      displayName: 'Build & Push ${{ service }}'
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - checkout: self
        - task: Docker@2
          displayName: 'Build & Push ${{ service }}'
          inputs:
            containerRegistry: 'ACR-ServiceConnection'
            repository: '$(acrName)/${{ service }}'
            command: 'buildAndPush'
            Dockerfile: 'app/${{ service }}/Dockerfile'
            tags: |
              $(Build.BuildId)

- stage: Deploy
  displayName: 'Deploy to Kubernetes'
  dependsOn: Build
  jobs:
    - ${{ each service in variables.services }}:
      - job: Deploy_${{ service }}
        displayName: 'Deploy ${{ service }}'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
          - task: Kubernetes@1
            displayName: 'Set image for ${{ service }}'
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceEndpoint: 'AKS-ServiceConnection'
              namespace: 'default'
              command: 'set'
              arguments: 'image deployment/${{ service }} ${{ service }}=$(acrName)/${{ service }}:$(Build.BuildId)'

          - task: Kubernetes@1
            displayName: 'Rollout restart ${{ service }}'
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceEndpoint: 'AKS-ServiceConnection'
              namespace: 'default'
              command: 'rollout'
              arguments: 'restart deployment/${{ service }}'
